package com.effort.settings;

import java.io.Serializable;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Configuration;
import org.springframework.stereotype.Component;

import com.effort.util.Log;



@Component
public class Constants implements Serializable {
	

	
	@Value("${disableInternFieldNamesForJsonObjectMapper}")
	private String disableInternFieldNamesForJsonObjectMapper;
	private String gspCropFormSpecUniqueId;
	private String rootEmpKey;
	private String glSTThresholdKey;
	private String mapToKey;
	private String jobsViaSms;
	private String jobsViaSmsKey;
	private String glGPSThresholdKey;
	private boolean gspCropFollowingWorkflow;
	private String jmsDestinationForJobAddOrModifi;
	private int gspCropNextScheduleInterval;
	private String formSpecUniqueId_Of_Approval_form_to_call_rest_call_api;
	private String jco_error_mail_address;
	public static final int CHANGE_TYPE_ADD = 1;
	public static final int CHANGE_TYPE_MODIFY = 2;
	public static final int FORM_FIELD_TYPE_CUSTOMER = 7;
	
	public static final String AUTOGENSEQ_SEPERATOR_1 = "-";
	public static final String AUTOGENSEQ_SEPERATOR_2 = "/";

	@Value("${debugLogEnable:false}")
	private Boolean debugLogEnable;
	private String rejectedBySytemDueToFormModify = "Rejected by the system because Form Template withdrawn";
	private Long global_company_customer_form_last_activity_time_skeleton_field_spec_id;
	private Long global_company_customer_form_last_activity_name_skeleton_field_spec_id;
	private Long global_company_customer_form_spec_id;
	private Long sales_new_leads_form_spec_id;
	private Integer placeHoldersGroupLimit;
	public static final int FORM_FIELD_TYPE_TEXT = 1;
	public static final int FORM_FIELD_TYPE_YES_NO = 4;
	public static final int FORM_FIELD_TYPE_RICH_TEXT = 35;
	public static final int FORM_FIELD_TYPE_NUMBER = 2;
	public static final int FORM_FIELD_TYPE_EMAIL = 8;
	public static final int FORM_FIELD_TYPE_PHONE = 9;
	public static final int FORM_FIELD_TYPE_URL = 10;
	public static final int FORM_FIELD_TYPE_TIME = 11;
	public static final int FORM_FIELD_TYPE_IMAGE = 12;
	public static final int FORM_FIELD_TYPE_SIGNATURE = 13;
	public static final int FORM_FIELD_TYPE_LIST = 14;
	public static final int FORM_FIELD_TYPE_EMPLOYEE = 15;
	public static final int FORM_FIELD_TYPE_CURRENCY = 16;
	public static final int FORM_FIELD_TYPE_MULTIPICK_LIST = 17;
	public static final int FORM_FIELD_TYPE_LOCATION = 18;
	public static final int FORM_FIELD_TYPE_DATE_TIME = 19;
	public static final int FORM_FIELD_TYPE_COUNTRY = 20;
	public static final int FORM_FIELD_TYPE_FINGER_PRINT = 21;
	public static final int FORM_FIELD_TYPE_AUDIO = 22;
	public static final int FORM_FIELD_TYPE_NUMBER_TO_WORD = 23;
	public static final int FORM_FIELD_TYPE_CUSTOMER_TYPE = 24;
	public static final int FORM_FIELD_TYPE_FORM = 25;
	public static final int FORM_FIELD_TYPE_TIMESPAN = 26;
	public static final int FORM_FIELD_TYPE_VIDEO = 27;
	public static final int FORM_FIELD_TYPE_AUTOGENERATED = 28;
	public static final int FORM_FIELD_TYPE_LABEL = 29;
	public static final int FORM_FIELD_TYPE_MULTIPICK_CUSTOMER = 30;
	public static final int FORM_FIELD_TYPE_TERRITORY = 31;
	public static final int FORM_FIELD_TYPE_CUSTOM_ENTITY = 32;
	public static final int FORM_FIELD_TYPE_MULTI_MEDIA = 33;
	public static final int FORM_FIELD_TYPE_MULTIPICK_CUSTOM_ENTITY = 49;
	public static final int CHANGE_TYPE_DELETE = 3;
	public static final int FORM_FIELD_TYPE_MONTH = 34;
	public static final int FORM_FIELD_TYPE_RICH_TEXT_FORMAT = 35;
	public static final int FORM_FIELD_TYPE_DATE = 3;
	public static final int FORM_CUSTOMER_FILTER_TYPE_CUSTOMERS_IN_MY_HIERARCHY = 2;
	public static final int FORM_CUSTOMER_FILTER_TYPE_ALL_CUSTOMERS = 1;
	public static final int FORM_FIELD_TYPE_MULTI_SELECT_LIST = 6;
	public static final int FORM_FIELD_TYPE_SINGLE_SELECT_LIST = 5;
	public static final String ACTION_TYPE_SYNC = "sync";
	private boolean printLogs;
	
	private String signInActivitiyVisibilityKey;
	private Long service_call_service_rendered_form_spec_id;
	private Long service_call_payment_collection_and_feedback_form_spec_id;
	private Long service_call_service_rendered_serviced_product_details_form_section_spec_id;
	private Long system_defined_max_imageSize_for_type_image;
	private Long service_call_service_rendered_product_form_section_field_spec_id;
	private Long service_call_service_rendered_part_form_section_field_spec_id;
	private Long service_call_service_rendered_in_warranty_form_section_field_spec_id;
	private Long service_call_service_rendered_in_warranty_amount_form_section_field_spec_id;
	private Long service_call_service_rendered_out_warranty_form_section_field_spec_id;
	private Long service_call_service_rendered_tax_amount_form_section_field_spec_id;
	private Long service_call_service_rendered_quantity_form_section_field_spec_id;
	private Long service_call_service_rendered_amount_form_section_field_spec_id;
	private Long service_call_service_rendered_amount_tax_form_section_field_spec_id;

	private Long service_call_service_rendered_customer_form_field_spec_id;
	private Long service_call_service_rendered_total_amount_form_field_spec_id;
	private Long service_call_service_rendered_total_tax_form_field_spec_id;
	private Long service_call_service_rendered_grand_total_form_field_spec_id;
	private Long service_call_service_rendered_remarks_form_field_spec_id;

	private Long service_call_payment_collection_and_feedback_customer_form_field_spec_id;
	private Long service_call_payment_collection_and_feedback_payment_amount_form_field_spec_id;
	private Long service_call_payment_collection_and_feedback_payment_mode_form_field_spec_id;
	private Long service_call_payment_collection_and_feedback_payment_particulars_form_field_spec_id;
	private Long service_call_payment_collection_and_feedback_remarks_form_field_spec_id;
	private Long service_call_payment_collection_and_feedback_responsiveness_form_field_spec_id;
	private Long service_call_payment_collection_and_feedback_competence_form_field_spec_id;
	private Long service_call_payment_collection_and_feedback_quality_of_work_form_field_spec_id;
	private Long service_call_payment_collection_and_feedback_your_satisfaction_level_form_field_spec_id;
	private Long service_call_payment_collection_and_feedback_suggestions_form_field_spec_id;
	private Long service_call_payment_collection_and_feedback_area_of_improvement_form_field_spec_id;
	private Long service_call_payment_collection_and_feedback_signature_form_field_spec_id;

	private Long service_call_service_rendered_product_entity_spec_id;
	private Long service_call_service_rendered_part_entity_spec_id;
	// private Long service_call_employee_skill_sets_entity_spec_id;
	private Long service_call_employee_payment_options_entity_spec_id;

	private Long service_call_product_product_entity_field_spec_id;
	private Long service_call_product_product_code_entity_field_spec_id;
	private Long service_call_product_description_entity_field_spec_id;

	private Long service_call_part_part_entity_field_spec_id;
	private Long service_call_part_product_entity_field_spec_id;
	private Long service_call_part_in_warranty_cost_entity_field_spec_id;
	private Long service_call_part_out_warranty_cost_entity_field_spec_id;
	private Long service_call_part_tax_rate_entity_field_spec_id;

	
	private Long sales_new_leads_name_form_field_spec_id;
	private Long sales_new_leads_primary_contact_first_name_form_field_spec_id;
	private Long sales_new_leads_primary_contact_last_name_form_field_spec_id;
	private Long sales_new_leads_primary_contact_phone_form_field_spec_id;
	private Long sales_new_leads_primary_contact_email_form_field_spec_id;
	private Long sales_new_leads_primary_contact_interested_products_form_field_spec_id;
	private Long sales_new_leads_primary_contact_estimated_value_form_field_spec_id;

	private Long sales_payment_collection_customer_form_field_spec_id;
	private Long sales_payment_collection_payment_amount_form_field_spec_id;
	private Long sales_payment_collection_payment_mode_form_field_spec_id;
	private Long sales_payment_collection_payment_particulars_form_field_spec_id;
	private Long sales_payment_collection_remarks_form_field_spec_id;
	private Long sales_payment_collection_customer_signature_form_field_spec_id;
	private Long system_defined_min_imageSize_for_type_image;
	private Long sales_orderform_orderitems_form_section_spec_id;
	private Long sales_orderform_item_form_section_field_spec_id;
	private Long sales_orderform_price_unit_form_section_field_spec_id;
	private Long sales_orderform_quantity_form_section_field_spec_id;
	private Long sales_orderform_amount_form_section_field_spec_id;

	private Long sales_orderform_customer_form_field_spec_id;
	private Long sales_orderform_discount_form_field_spec_id;
	private Long sales_orderform_tax_percentage_form_field_spec_id;
	private Long sales_orderform_total_amount_form_field_spec_id;
	private Long sales_orderform_delivery_date_form_field_spec_id;
	private Long sales_orderform_signature_form_field_spec_id;
	private Long fizikem_branch_skeleton_entityFieldSpecId;
	
	private long emp_branch_list_specId;
	private String gspCropFormFieldSpecformIDUniqueId;
	private Long serivce_call_Job_form_specId;
	private Long service_call_visit_type;
	private String signOutConditionKey;
	
	private String latest_client_production_version;
	private String mediaStoragePath; 
	private String jmsDestination;	
	
	private Long tvsDeliveryWorkSpecId;
	private String tvsZoneUserFormFieldUniqueId;
	private long tvsZoneEmployeesEntitySpecId;
	private long tvsZoneEmployeesEmployeeNameEntityFieldSpecId;
	private Long skeletonWorkEmployeeFieldSpecId;
	private Long telenor_company_work_action_specId_reject_retailer;
	// Form Customer Filter
	public static final int FORM_CUSTOMER_FILTER_TYPE_CUSTOMERS_MAPPED_TO_ME = 3;
	public static final int FORM_CUSTOMER_FILTER_TYPE_CUSTOMERS_ME_AND_MY_HIERARCHY = 4;
	
	//form field skeleton spec id
		private Long skeletonWorkNameFieldSpecId;
		private Long skeletonWorkDescriptionFieldSpecId;
		private Long skeletonWorkStartsFieldSpecId;
		private Long skeletonWorkEndsFieldSpecId;
		private String skeletonCustomerFieldSpecId;
		private Long skeletonWorkProrityFieldSpecId;
		private String skeletonCustomerAddressFieldSpecId;
		private Long skeletonWorkPhoneNumberFieldSpecId;
		private Long skeletonWorkStreetFieldSpecId;
		private Long skeletonWorkAreaFieldSpecId;
		private Long skeletonWorkCityFieldSpecId;
		private Long skeletonWorkLandMarkFieldSpecId;
		private Long skeletonWorkCountryFieldSpecId;
		private Long skeletonWorkStateFieldSpecId;
		private Long skeletonWorkPincodeFieldSpecId;
		private Long skeletonWorkLocationFieldSpecId;
		private String captureLocationInFormUpdateKey;
		private boolean captureLocationInFormUpdate;
	
		
        public long global_company_custom_entity_form_spec_id;
		private long global_company_skeleton_entityName_field_spec_id;
		private long global_company_skeleton_entityId_field_spec_id;
		private long global_company_skeleton_location_field_spec_id;
		
		private Long ltf_fi_workspec_id;
		private Long ltf_rcu_workspec_id;
		private Long ltf_mcm_workspec_id;
		private Long ltf_fi_farm_workspec_id;
		private String ltf_fi_work_vendor_field_unique_id;
		private boolean captureLocationInFormMediaUpdate;
		@Value("${map.customEntitySpecToEmployeeKey}")
		private String mapCustomEntitySpecToEmployeeKey;
		private String captureLocationInFormMediaKey;

		
		private String ltf_rcu_work_vendor_field_unique_id;
		private Long ltf_fi_rcu_vendor_city_spoc_mapping_entitySpecId;
		private Long ltf_fi_rcu_vendor_city_spoc_mapping_spoc_id_entityFieldSpecId;
		private String ltf_fi_work_city_field_unique_id;
		private String ltf_rcu_work_city_field_unique_id;
		private Integer xeroxCompanyId;
		private String pushNotificationDefaultMessage;
		
		private String windowsPushNotificationAccessTokenHeaderContentType;
		private String windowsPushNotificationAccessTokenParameterString;
		private String windowsPushNotificationAccessTokenUrl;
		private String mediaBaseUrl;
		private String supportingImgExtn;
		private String gspCropquantitySectionFieldSpecUniqueId;

		private static String project;
    public static int getChangeTypeDelete() {
		return CHANGE_TYPE_DELETE;
	}
	public static int getFormFieldTypeCustomer() {
		return FORM_FIELD_TYPE_CUSTOMER;
	}
	
	public boolean isPrintLogs() {
		return printLogs;
	}
	public static int getChangeTypeModify() {
		return CHANGE_TYPE_MODIFY;
	}
	public static int getFormFieldTypeDate() {
		return FORM_FIELD_TYPE_DATE;
	}

	public void setPrintLogs(boolean printLogs) {
		this.printLogs = printLogs;
	}
	public String getDisableInternFieldNamesForJsonObjectMapper() {
		return disableInternFieldNamesForJsonObjectMapper;
	}
	public void setDisableInternFieldNamesForJsonObjectMapper(
			String disableInternFieldNamesForJsonObjectMapper) {
		this.disableInternFieldNamesForJsonObjectMapper = disableInternFieldNamesForJsonObjectMapper;
	}
	public Long getGlobal_company_customer_form_last_activity_time_skeleton_field_spec_id() {
		return global_company_customer_form_last_activity_time_skeleton_field_spec_id;
	}
	public void setGlobal_company_customer_form_last_activity_time_skeleton_field_spec_id(
			Long global_company_customer_form_last_activity_time_skeleton_field_spec_id) {
		this.global_company_customer_form_last_activity_time_skeleton_field_spec_id = global_company_customer_form_last_activity_time_skeleton_field_spec_id;
	}
	
	public String getRejectedBySytemDueToFormModify() {
		return rejectedBySytemDueToFormModify;
	}
	public Long getGlobal_company_customer_form_last_activity_name_skeleton_field_spec_id() {
		return global_company_customer_form_last_activity_name_skeleton_field_spec_id;
	}

	public void setRejectedBySytemDueToFormModify(
			String rejectedBySytemDueToFormModify) {
		this.rejectedBySytemDueToFormModify = rejectedBySytemDueToFormModify;
	}
	
	public Long getSales_new_leads_form_spec_id() {
		return sales_new_leads_form_spec_id;
	}
	public Integer getPlaceHoldersGroupLimit() {
		return placeHoldersGroupLimit;
	}

	public void setPlaceHoldersGroupLimit(Integer placeHoldersGroupLimit) {
		this.placeHoldersGroupLimit = placeHoldersGroupLimit;
	}
	
	public Boolean isDebugLogEnable() {
		return debugLogEnable;
	}
	
	public String getGspCropFormSpecUniqueId() {
		return gspCropFormSpecUniqueId;
	}
	

	public boolean isGspCropFollowingWorkflow() {
		return gspCropFollowingWorkflow;
	}
	
	public String getRootEmpKey() {
		return rootEmpKey;
	}
	
	public String getGlSTThresholdKey() {
		return glSTThresholdKey;
	}
	public String getGlGPSThresholdKey() {
		return glGPSThresholdKey;
	}

	public long getGlobal_company_customer_form_spec_id() {
		return global_company_customer_form_spec_id;
	}
	public static int getFormFieldTypeNumber() {
		return FORM_FIELD_TYPE_NUMBER;
	}
	
	
	
	public String getMapToKey() {
		return mapToKey;
	}
	
	public String getJco_error_mail_address() {
		return jco_error_mail_address;
	}
	
	
	public String getJmsDestinationForJobAddOrModifi() {
		return jmsDestinationForJobAddOrModifi;
	}
	public String getJobsViaSmsKey() {
		return jobsViaSmsKey;
	}
	public int getGspCropNextScheduleInterval() {
		return gspCropNextScheduleInterval;
	}
	public String getFormSpecUniqueId_Of_Approval_form_to_call_rest_call_api() {
		return formSpecUniqueId_Of_Approval_form_to_call_rest_call_api;
	}
	
	public Long getService_call_service_rendered_form_spec_id() {
		return service_call_service_rendered_form_spec_id;
	}

	public void setService_call_service_rendered_form_spec_id(
			Long service_call_service_rendered_form_spec_id) {
		this.service_call_service_rendered_form_spec_id = service_call_service_rendered_form_spec_id;
	}

	public Long getService_call_payment_collection_and_feedback_form_spec_id() {
		return service_call_payment_collection_and_feedback_form_spec_id;
	}

	public void setService_call_payment_collection_and_feedback_form_spec_id(
			Long service_call_payment_collection_and_feedback_form_spec_id) {
		this.service_call_payment_collection_and_feedback_form_spec_id = service_call_payment_collection_and_feedback_form_spec_id;
	}

	public Long getService_call_service_rendered_serviced_product_details_form_section_spec_id() {
		return service_call_service_rendered_serviced_product_details_form_section_spec_id;
	}

	public void setService_call_service_rendered_serviced_product_details_form_section_spec_id(
			Long service_call_service_rendered_serviced_product_details_form_section_spec_id) {
		this.service_call_service_rendered_serviced_product_details_form_section_spec_id = service_call_service_rendered_serviced_product_details_form_section_spec_id;
	}

	public Long getService_call_service_rendered_product_form_section_field_spec_id() {
		return service_call_service_rendered_product_form_section_field_spec_id;
	}

	public void setService_call_service_rendered_product_form_section_field_spec_id(
			Long service_call_service_rendered_product_form_section_field_spec_id) {
		this.service_call_service_rendered_product_form_section_field_spec_id = service_call_service_rendered_product_form_section_field_spec_id;
	}

	public Long getService_call_service_rendered_part_form_section_field_spec_id() {
		return service_call_service_rendered_part_form_section_field_spec_id;
	}

	public void setService_call_service_rendered_part_form_section_field_spec_id(
			Long service_call_service_rendered_part_form_section_field_spec_id) {
		this.service_call_service_rendered_part_form_section_field_spec_id = service_call_service_rendered_part_form_section_field_spec_id;
	}

	public Long getService_call_service_rendered_in_warranty_form_section_field_spec_id() {
		return service_call_service_rendered_in_warranty_form_section_field_spec_id;
	}

	public void setService_call_service_rendered_in_warranty_form_section_field_spec_id(
			Long service_call_service_rendered_in_warranty_form_section_field_spec_id) {
		this.service_call_service_rendered_in_warranty_form_section_field_spec_id = service_call_service_rendered_in_warranty_form_section_field_spec_id;
	}

	public Long getService_call_service_rendered_in_warranty_amount_form_section_field_spec_id() {
		return service_call_service_rendered_in_warranty_amount_form_section_field_spec_id;
	}

	public void setService_call_service_rendered_in_warranty_amount_form_section_field_spec_id(
			Long service_call_service_rendered_in_warranty_amount_form_section_field_spec_id) {
		this.service_call_service_rendered_in_warranty_amount_form_section_field_spec_id = service_call_service_rendered_in_warranty_amount_form_section_field_spec_id;
	}

	public Long getService_call_service_rendered_out_warranty_form_section_field_spec_id() {
		return service_call_service_rendered_out_warranty_form_section_field_spec_id;
	}

	public void setService_call_service_rendered_out_warranty_form_section_field_spec_id(
			Long service_call_service_rendered_out_warranty_form_section_field_spec_id) {
		this.service_call_service_rendered_out_warranty_form_section_field_spec_id = service_call_service_rendered_out_warranty_form_section_field_spec_id;
	}

	public Long getService_call_service_rendered_tax_amount_form_section_field_spec_id() {
		return service_call_service_rendered_tax_amount_form_section_field_spec_id;
	}

	public void setService_call_service_rendered_tax_amount_form_section_field_spec_id(
			Long service_call_service_rendered_tax_amount_form_section_field_spec_id) {
		this.service_call_service_rendered_tax_amount_form_section_field_spec_id = service_call_service_rendered_tax_amount_form_section_field_spec_id;
	}

	public Long getService_call_service_rendered_quantity_form_section_field_spec_id() {
		return service_call_service_rendered_quantity_form_section_field_spec_id;
	}

	public void setService_call_service_rendered_quantity_form_section_field_spec_id(
			Long service_call_service_rendered_quantity_form_section_field_spec_id) {
		this.service_call_service_rendered_quantity_form_section_field_spec_id = service_call_service_rendered_quantity_form_section_field_spec_id;
	}

	public Long getService_call_service_rendered_amount_form_section_field_spec_id() {
		return service_call_service_rendered_amount_form_section_field_spec_id;
	}

	public void setService_call_service_rendered_amount_form_section_field_spec_id(
			Long service_call_service_rendered_amount_form_section_field_spec_id) {
		this.service_call_service_rendered_amount_form_section_field_spec_id = service_call_service_rendered_amount_form_section_field_spec_id;
	}

	public Long getService_call_service_rendered_amount_tax_form_section_field_spec_id() {
		return service_call_service_rendered_amount_tax_form_section_field_spec_id;
	}

	public void setService_call_service_rendered_amount_tax_form_section_field_spec_id(
			Long service_call_service_rendered_amount_tax_form_section_field_spec_id) {
		this.service_call_service_rendered_amount_tax_form_section_field_spec_id = service_call_service_rendered_amount_tax_form_section_field_spec_id;
	}

	public Long getService_call_service_rendered_customer_form_field_spec_id() {
		return service_call_service_rendered_customer_form_field_spec_id;
	}

	public void setService_call_service_rendered_customer_form_field_spec_id(
			Long service_call_service_rendered_customer_form_field_spec_id) {
		this.service_call_service_rendered_customer_form_field_spec_id = service_call_service_rendered_customer_form_field_spec_id;
	}

	public Long getService_call_service_rendered_total_amount_form_field_spec_id() {
		return service_call_service_rendered_total_amount_form_field_spec_id;
	}

	public void setService_call_service_rendered_total_amount_form_field_spec_id(
			Long service_call_service_rendered_total_amount_form_field_spec_id) {
		this.service_call_service_rendered_total_amount_form_field_spec_id = service_call_service_rendered_total_amount_form_field_spec_id;
	}

	public Long getService_call_service_rendered_total_tax_form_field_spec_id() {
		return service_call_service_rendered_total_tax_form_field_spec_id;
	}

	public void setService_call_service_rendered_total_tax_form_field_spec_id(
			Long service_call_service_rendered_total_tax_form_field_spec_id) {
		this.service_call_service_rendered_total_tax_form_field_spec_id = service_call_service_rendered_total_tax_form_field_spec_id;
	}

	public Long getService_call_service_rendered_grand_total_form_field_spec_id() {
		return service_call_service_rendered_grand_total_form_field_spec_id;
	}

	public void setService_call_service_rendered_grand_total_form_field_spec_id(
			Long service_call_service_rendered_grand_total_form_field_spec_id) {
		this.service_call_service_rendered_grand_total_form_field_spec_id = service_call_service_rendered_grand_total_form_field_spec_id;
	}

	public Long getService_call_service_rendered_remarks_form_field_spec_id() {
		return service_call_service_rendered_remarks_form_field_spec_id;
	}

	public void setService_call_service_rendered_remarks_form_field_spec_id(
			Long service_call_service_rendered_remarks_form_field_spec_id) {
		this.service_call_service_rendered_remarks_form_field_spec_id = service_call_service_rendered_remarks_form_field_spec_id;
	}

	public Long getService_call_payment_collection_and_feedback_customer_form_field_spec_id() {
		return service_call_payment_collection_and_feedback_customer_form_field_spec_id;
	}

	public void setService_call_payment_collection_and_feedback_customer_form_field_spec_id(
			Long service_call_payment_collection_and_feedback_customer_form_field_spec_id) {
		this.service_call_payment_collection_and_feedback_customer_form_field_spec_id = service_call_payment_collection_and_feedback_customer_form_field_spec_id;
	}

	public Long getService_call_payment_collection_and_feedback_payment_amount_form_field_spec_id() {
		return service_call_payment_collection_and_feedback_payment_amount_form_field_spec_id;
	}

	public void setService_call_payment_collection_and_feedback_payment_amount_form_field_spec_id(
			Long service_call_payment_collection_and_feedback_payment_amount_form_field_spec_id) {
		this.service_call_payment_collection_and_feedback_payment_amount_form_field_spec_id = service_call_payment_collection_and_feedback_payment_amount_form_field_spec_id;
	}

	public Long getService_call_payment_collection_and_feedback_payment_mode_form_field_spec_id() {
		return service_call_payment_collection_and_feedback_payment_mode_form_field_spec_id;
	}

	public void setService_call_payment_collection_and_feedback_payment_mode_form_field_spec_id(
			Long service_call_payment_collection_and_feedback_payment_mode_form_field_spec_id) {
		this.service_call_payment_collection_and_feedback_payment_mode_form_field_spec_id = service_call_payment_collection_and_feedback_payment_mode_form_field_spec_id;
	}

	public Long getService_call_payment_collection_and_feedback_payment_particulars_form_field_spec_id() {
		return service_call_payment_collection_and_feedback_payment_particulars_form_field_spec_id;
	}

	public void setService_call_payment_collection_and_feedback_payment_particulars_form_field_spec_id(
			Long service_call_payment_collection_and_feedback_payment_particulars_form_field_spec_id) {
		this.service_call_payment_collection_and_feedback_payment_particulars_form_field_spec_id = service_call_payment_collection_and_feedback_payment_particulars_form_field_spec_id;
	}

	public Long getService_call_payment_collection_and_feedback_remarks_form_field_spec_id() {
		return service_call_payment_collection_and_feedback_remarks_form_field_spec_id;
	}

	public void setService_call_payment_collection_and_feedback_remarks_form_field_spec_id(
			Long service_call_payment_collection_and_feedback_remarks_form_field_spec_id) {
		this.service_call_payment_collection_and_feedback_remarks_form_field_spec_id = service_call_payment_collection_and_feedback_remarks_form_field_spec_id;
	}

	public Long getService_call_payment_collection_and_feedback_responsiveness_form_field_spec_id() {
		return service_call_payment_collection_and_feedback_responsiveness_form_field_spec_id;
	}

	public void setService_call_payment_collection_and_feedback_responsiveness_form_field_spec_id(
			Long service_call_payment_collection_and_feedback_responsiveness_form_field_spec_id) {
		this.service_call_payment_collection_and_feedback_responsiveness_form_field_spec_id = service_call_payment_collection_and_feedback_responsiveness_form_field_spec_id;
	}

	public Long getService_call_payment_collection_and_feedback_competence_form_field_spec_id() {
		return service_call_payment_collection_and_feedback_competence_form_field_spec_id;
	}

	public void setService_call_payment_collection_and_feedback_competence_form_field_spec_id(
			Long service_call_payment_collection_and_feedback_competence_form_field_spec_id) {
		this.service_call_payment_collection_and_feedback_competence_form_field_spec_id = service_call_payment_collection_and_feedback_competence_form_field_spec_id;
	}

	public Long getService_call_payment_collection_and_feedback_quality_of_work_form_field_spec_id() {
		return service_call_payment_collection_and_feedback_quality_of_work_form_field_spec_id;
	}

	public void setService_call_payment_collection_and_feedback_quality_of_work_form_field_spec_id(
			Long service_call_payment_collection_and_feedback_quality_of_work_form_field_spec_id) {
		this.service_call_payment_collection_and_feedback_quality_of_work_form_field_spec_id = service_call_payment_collection_and_feedback_quality_of_work_form_field_spec_id;
	}

	public Long getService_call_payment_collection_and_feedback_your_satisfaction_level_form_field_spec_id() {
		return service_call_payment_collection_and_feedback_your_satisfaction_level_form_field_spec_id;
	}

	public void setService_call_payment_collection_and_feedback_your_satisfaction_level_form_field_spec_id(
			Long service_call_payment_collection_and_feedback_your_satisfaction_level_form_field_spec_id) {
		this.service_call_payment_collection_and_feedback_your_satisfaction_level_form_field_spec_id = service_call_payment_collection_and_feedback_your_satisfaction_level_form_field_spec_id;
	}

	public Long getService_call_payment_collection_and_feedback_suggestions_form_field_spec_id() {
		return service_call_payment_collection_and_feedback_suggestions_form_field_spec_id;
	}

	public void setService_call_payment_collection_and_feedback_suggestions_form_field_spec_id(
			Long service_call_payment_collection_and_feedback_suggestions_form_field_spec_id) {
		this.service_call_payment_collection_and_feedback_suggestions_form_field_spec_id = service_call_payment_collection_and_feedback_suggestions_form_field_spec_id;
	}

	public Long getService_call_payment_collection_and_feedback_area_of_improvement_form_field_spec_id() {
		return service_call_payment_collection_and_feedback_area_of_improvement_form_field_spec_id;
	}

	public void setService_call_payment_collection_and_feedback_area_of_improvement_form_field_spec_id(
			Long service_call_payment_collection_and_feedback_area_of_improvement_form_field_spec_id) {
		this.service_call_payment_collection_and_feedback_area_of_improvement_form_field_spec_id = service_call_payment_collection_and_feedback_area_of_improvement_form_field_spec_id;
	}

	public Long getService_call_payment_collection_and_feedback_signature_form_field_spec_id() {
		return service_call_payment_collection_and_feedback_signature_form_field_spec_id;
	}

	public void setService_call_payment_collection_and_feedback_signature_form_field_spec_id(
			Long service_call_payment_collection_and_feedback_signature_form_field_spec_id) {
		this.service_call_payment_collection_and_feedback_signature_form_field_spec_id = service_call_payment_collection_and_feedback_signature_form_field_spec_id;
	}

	public Long getService_call_service_rendered_product_entity_spec_id() {
		return service_call_service_rendered_product_entity_spec_id;
	}

	public void setService_call_service_rendered_product_entity_spec_id(
			Long service_call_service_rendered_product_entity_spec_id) {
		this.service_call_service_rendered_product_entity_spec_id = service_call_service_rendered_product_entity_spec_id;
	}

	public Long getService_call_service_rendered_part_entity_spec_id() {
		return service_call_service_rendered_part_entity_spec_id;
	}

	public void setService_call_service_rendered_part_entity_spec_id(
			Long service_call_service_rendered_part_entity_spec_id) {
		this.service_call_service_rendered_part_entity_spec_id = service_call_service_rendered_part_entity_spec_id;
	}

	/*
	 * public Long getService_call_employee_skill_sets_entity_spec_id() { return
	 * service_call_employee_skill_sets_entity_spec_id; }
	 * 
	 * public void setService_call_employee_skill_sets_entity_spec_id( Long
	 * service_call_employee_skill_sets_entity_spec_id) {
	 * this.service_call_employee_skill_sets_entity_spec_id =
	 * service_call_employee_skill_sets_entity_spec_id; }
	 */

	public Long getService_call_employee_payment_options_entity_spec_id() {
		return service_call_employee_payment_options_entity_spec_id;
	}

	public void setService_call_employee_payment_options_entity_spec_id(
			Long service_call_employee_payment_options_entity_spec_id) {
		this.service_call_employee_payment_options_entity_spec_id = service_call_employee_payment_options_entity_spec_id;
	}

	public Long getService_call_product_product_entity_field_spec_id() {
		return service_call_product_product_entity_field_spec_id;
	}

	public void setService_call_product_product_entity_field_spec_id(
			Long service_call_product_product_entity_field_spec_id) {
		this.service_call_product_product_entity_field_spec_id = service_call_product_product_entity_field_spec_id;
	}

	public Long getService_call_product_product_code_entity_field_spec_id() {
		return service_call_product_product_code_entity_field_spec_id;
	}

	public void setService_call_product_product_code_entity_field_spec_id(
			Long service_call_product_product_code_entity_field_spec_id) {
		this.service_call_product_product_code_entity_field_spec_id = service_call_product_product_code_entity_field_spec_id;
	}

	public Long getService_call_product_description_entity_field_spec_id() {
		return service_call_product_description_entity_field_spec_id;
	}

	public void setService_call_product_description_entity_field_spec_id(
			Long service_call_product_description_entity_field_spec_id) {
		this.service_call_product_description_entity_field_spec_id = service_call_product_description_entity_field_spec_id;
	}

	public Long getService_call_part_part_entity_field_spec_id() {
		return service_call_part_part_entity_field_spec_id;
	}

	public void setService_call_part_part_entity_field_spec_id(
			Long service_call_part_part_entity_field_spec_id) {
		this.service_call_part_part_entity_field_spec_id = service_call_part_part_entity_field_spec_id;
	}

	public Long getService_call_part_product_entity_field_spec_id() {
		return service_call_part_product_entity_field_spec_id;
	}

	public void setService_call_part_product_entity_field_spec_id(
			Long service_call_part_product_entity_field_spec_id) {
		this.service_call_part_product_entity_field_spec_id = service_call_part_product_entity_field_spec_id;
	}

	public Long getService_call_part_in_warranty_cost_entity_field_spec_id() {
		return service_call_part_in_warranty_cost_entity_field_spec_id;
	}

	public void setService_call_part_in_warranty_cost_entity_field_spec_id(
			Long service_call_part_in_warranty_cost_entity_field_spec_id) {
		this.service_call_part_in_warranty_cost_entity_field_spec_id = service_call_part_in_warranty_cost_entity_field_spec_id;
	}

	public Long getService_call_part_out_warranty_cost_entity_field_spec_id() {
		return service_call_part_out_warranty_cost_entity_field_spec_id;
	}

	public void setService_call_part_out_warranty_cost_entity_field_spec_id(
			Long service_call_part_out_warranty_cost_entity_field_spec_id) {
		this.service_call_part_out_warranty_cost_entity_field_spec_id = service_call_part_out_warranty_cost_entity_field_spec_id;
	}

	public Long getService_call_part_tax_rate_entity_field_spec_id() {
		return service_call_part_tax_rate_entity_field_spec_id;
	}

	public void setService_call_part_tax_rate_entity_field_spec_id(
			Long service_call_part_tax_rate_entity_field_spec_id) {
		this.service_call_part_tax_rate_entity_field_spec_id = service_call_part_tax_rate_entity_field_spec_id;
	}

	public Long getSales_new_leads_name_form_field_spec_id() {
		return sales_new_leads_name_form_field_spec_id;
	}

	public void setSales_new_leads_name_form_field_spec_id(
			Long sales_new_leads_name_form_field_spec_id) {
		this.sales_new_leads_name_form_field_spec_id = sales_new_leads_name_form_field_spec_id;
	}

	public Long getSales_new_leads_primary_contact_first_name_form_field_spec_id() {
		return sales_new_leads_primary_contact_first_name_form_field_spec_id;
	}

	public void setSales_new_leads_primary_contact_first_name_form_field_spec_id(
			Long sales_new_leads_primary_contact_first_name_form_field_spec_id) {
		this.sales_new_leads_primary_contact_first_name_form_field_spec_id = sales_new_leads_primary_contact_first_name_form_field_spec_id;
	}

	public Long getSales_new_leads_primary_contact_last_name_form_field_spec_id() {
		return sales_new_leads_primary_contact_last_name_form_field_spec_id;
	}

	public void setSales_new_leads_primary_contact_last_name_form_field_spec_id(
			Long sales_new_leads_primary_contact_last_name_form_field_spec_id) {
		this.sales_new_leads_primary_contact_last_name_form_field_spec_id = sales_new_leads_primary_contact_last_name_form_field_spec_id;
	}

	public Long getSales_new_leads_primary_contact_phone_form_field_spec_id() {
		return sales_new_leads_primary_contact_phone_form_field_spec_id;
	}

	public void setSales_new_leads_primary_contact_phone_form_field_spec_id(
			Long sales_new_leads_primary_contact_phone_form_field_spec_id) {
		this.sales_new_leads_primary_contact_phone_form_field_spec_id = sales_new_leads_primary_contact_phone_form_field_spec_id;
	}

	public Long getSales_new_leads_primary_contact_email_form_field_spec_id() {
		return sales_new_leads_primary_contact_email_form_field_spec_id;
	}

	public void setSales_new_leads_primary_contact_email_form_field_spec_id(
			Long sales_new_leads_primary_contact_email_form_field_spec_id) {
		this.sales_new_leads_primary_contact_email_form_field_spec_id = sales_new_leads_primary_contact_email_form_field_spec_id;
	}

	public Long getSales_new_leads_primary_contact_interested_products_form_field_spec_id() {
		return sales_new_leads_primary_contact_interested_products_form_field_spec_id;
	}

	public void setSales_new_leads_primary_contact_interested_products_form_field_spec_id(
			Long sales_new_leads_primary_contact_interested_products_form_field_spec_id) {
		this.sales_new_leads_primary_contact_interested_products_form_field_spec_id = sales_new_leads_primary_contact_interested_products_form_field_spec_id;
	}

	public Long getSales_new_leads_primary_contact_estimated_value_form_field_spec_id() {
		return sales_new_leads_primary_contact_estimated_value_form_field_spec_id;
	}

	public void setSales_new_leads_primary_contact_estimated_value_form_field_spec_id(
			Long sales_new_leads_primary_contact_estimated_value_form_field_spec_id) {
		this.sales_new_leads_primary_contact_estimated_value_form_field_spec_id = sales_new_leads_primary_contact_estimated_value_form_field_spec_id;
	}

	public Long getSales_payment_collection_customer_form_field_spec_id() {
		return sales_payment_collection_customer_form_field_spec_id;
	}

	public void setSales_payment_collection_customer_form_field_spec_id(
			Long sales_payment_collection_customer_form_field_spec_id) {
		this.sales_payment_collection_customer_form_field_spec_id = sales_payment_collection_customer_form_field_spec_id;
	}

	public Long getSales_payment_collection_payment_amount_form_field_spec_id() {
		return sales_payment_collection_payment_amount_form_field_spec_id;
	}

	public void setSales_payment_collection_payment_amount_form_field_spec_id(
			Long sales_payment_collection_payment_amount_form_field_spec_id) {
		this.sales_payment_collection_payment_amount_form_field_spec_id = sales_payment_collection_payment_amount_form_field_spec_id;
	}

	public Long getSales_payment_collection_payment_mode_form_field_spec_id() {
		return sales_payment_collection_payment_mode_form_field_spec_id;
	}

	public void setSales_payment_collection_payment_mode_form_field_spec_id(
			Long sales_payment_collection_payment_mode_form_field_spec_id) {
		this.sales_payment_collection_payment_mode_form_field_spec_id = sales_payment_collection_payment_mode_form_field_spec_id;
	}

	public Long getSales_payment_collection_payment_particulars_form_field_spec_id() {
		return sales_payment_collection_payment_particulars_form_field_spec_id;
	}

	public void setSales_payment_collection_payment_particulars_form_field_spec_id(
			Long sales_payment_collection_payment_particulars_form_field_spec_id) {
		this.sales_payment_collection_payment_particulars_form_field_spec_id = sales_payment_collection_payment_particulars_form_field_spec_id;
	}

	public Long getSales_payment_collection_remarks_form_field_spec_id() {
		return sales_payment_collection_remarks_form_field_spec_id;
	}

	public void setSales_payment_collection_remarks_form_field_spec_id(
			Long sales_payment_collection_remarks_form_field_spec_id) {
		this.sales_payment_collection_remarks_form_field_spec_id = sales_payment_collection_remarks_form_field_spec_id;
	}

	public Long getSales_payment_collection_customer_signature_form_field_spec_id() {
		return sales_payment_collection_customer_signature_form_field_spec_id;
	}

	public void setSales_payment_collection_customer_signature_form_field_spec_id(
			Long sales_payment_collection_customer_signature_form_field_spec_id) {
		this.sales_payment_collection_customer_signature_form_field_spec_id = sales_payment_collection_customer_signature_form_field_spec_id;
	}

	public Long getSales_orderform_orderitems_form_section_spec_id() {
		return sales_orderform_orderitems_form_section_spec_id;
	}

	public void setSales_orderform_orderitems_form_section_spec_id(
			Long sales_orderform_orderitems_form_section_spec_id) {
		this.sales_orderform_orderitems_form_section_spec_id = sales_orderform_orderitems_form_section_spec_id;
	}

	public Long getSales_orderform_item_form_section_field_spec_id() {
		return sales_orderform_item_form_section_field_spec_id;
	}

	public void setSales_orderform_item_form_section_field_spec_id(
			Long sales_orderform_item_form_section_field_spec_id) {
		this.sales_orderform_item_form_section_field_spec_id = sales_orderform_item_form_section_field_spec_id;
	}

	public Long getSales_orderform_price_unit_form_section_field_spec_id() {
		return sales_orderform_price_unit_form_section_field_spec_id;
	}

	public void setSales_orderform_price_unit_form_section_field_spec_id(
			Long sales_orderform_price_unit_form_section_field_spec_id) {
		this.sales_orderform_price_unit_form_section_field_spec_id = sales_orderform_price_unit_form_section_field_spec_id;
	}

	public Long getSales_orderform_quantity_form_section_field_spec_id() {
		return sales_orderform_quantity_form_section_field_spec_id;
	}

	public void setSales_orderform_quantity_form_section_field_spec_id(
			Long sales_orderform_quantity_form_section_field_spec_id) {
		this.sales_orderform_quantity_form_section_field_spec_id = sales_orderform_quantity_form_section_field_spec_id;
	}

	public Long getSales_orderform_amount_form_section_field_spec_id() {
		return sales_orderform_amount_form_section_field_spec_id;
	}

	public void setSales_orderform_amount_form_section_field_spec_id(
			Long sales_orderform_amount_form_section_field_spec_id) {
		this.sales_orderform_amount_form_section_field_spec_id = sales_orderform_amount_form_section_field_spec_id;
	}

	public Long getSales_orderform_customer_form_field_spec_id() {
		return sales_orderform_customer_form_field_spec_id;
	}

	public void setSales_orderform_customer_form_field_spec_id(
			Long sales_orderform_customer_form_field_spec_id) {
		this.sales_orderform_customer_form_field_spec_id = sales_orderform_customer_form_field_spec_id;
	}

	public Long getSales_orderform_discount_form_field_spec_id() {
		return sales_orderform_discount_form_field_spec_id;
	}

	public void setSales_orderform_discount_form_field_spec_id(
			Long sales_orderform_discount_form_field_spec_id) {
		this.sales_orderform_discount_form_field_spec_id = sales_orderform_discount_form_field_spec_id;
	}

	public Long getSales_orderform_tax_percentage_form_field_spec_id() {
		return sales_orderform_tax_percentage_form_field_spec_id;
	}

	public void setSales_orderform_tax_percentage_form_field_spec_id(
			Long sales_orderform_tax_percentage_form_field_spec_id) {
		this.sales_orderform_tax_percentage_form_field_spec_id = sales_orderform_tax_percentage_form_field_spec_id;
	}

	public Long getSales_orderform_total_amount_form_field_spec_id() {
		return sales_orderform_total_amount_form_field_spec_id;
	}

	public void setSales_orderform_total_amount_form_field_spec_id(
			Long sales_orderform_total_amount_form_field_spec_id) {
		this.sales_orderform_total_amount_form_field_spec_id = sales_orderform_total_amount_form_field_spec_id;
	}

	public Long getSales_orderform_delivery_date_form_field_spec_id() {
		return sales_orderform_delivery_date_form_field_spec_id;
	}

	public void setSales_orderform_delivery_date_form_field_spec_id(
			Long sales_orderform_delivery_date_form_field_spec_id) {
		this.sales_orderform_delivery_date_form_field_spec_id = sales_orderform_delivery_date_form_field_spec_id;
	}

	public Long getSales_orderform_signature_form_field_spec_id() {
		return sales_orderform_signature_form_field_spec_id;
	}

	public void setSales_orderform_signature_form_field_spec_id(
			Long sales_orderform_signature_form_field_spec_id) {
		this.sales_orderform_signature_form_field_spec_id = sales_orderform_signature_form_field_spec_id;
	}
	public long getEmp_branch_list_specId() {
		return emp_branch_list_specId;
	}


	public String getGspCropFormFieldSpecformIDUniqueId() {
		return gspCropFormFieldSpecformIDUniqueId;
	}
	public Long getFizikem_branch_skeleton_entityFieldSpecId() {
		return fizikem_branch_skeleton_entityFieldSpecId;
	}
	public Long getSerivce_call_Job_form_specId() {
		return serivce_call_Job_form_specId;
	}
	public Long getService_call_visit_type() {
		return service_call_visit_type;
	}
	public String getLatest_client_production_version() {
		return latest_client_production_version;
	}
	
	public Long getSystem_defined_max_imageSize_for_type_image() {
		return system_defined_max_imageSize_for_type_image;
	}
	
	public Long getSystem_defined_min_imageSize_for_type_image() {
		return system_defined_min_imageSize_for_type_image;
	}

	public String getMediaStoragePath() {
		return mediaStoragePath;
	}
	public String getJmsDestination() {
		return jmsDestination;
	}
	

	public long getTvsDeliveryWorkSpecId() {
		return tvsDeliveryWorkSpecId;
	}

	public void setTvsDeliveryWorkSpecId(long tvsDeliveryWorkSpecId) {
		this.tvsDeliveryWorkSpecId = tvsDeliveryWorkSpecId;
	}
	public String getTvsZoneUserFormFieldUniqueId() {
		return tvsZoneUserFormFieldUniqueId;
	}

	public void setTvsZoneUserFormFieldUniqueId(String tvsZoneUserFormFieldUniqueId) {
		this.tvsZoneUserFormFieldUniqueId = tvsZoneUserFormFieldUniqueId;
	}
	
	public long getTvsZoneEmployeesEntitySpecId() {
		return tvsZoneEmployeesEntitySpecId;
	}

	public void setTvsZoneEmployeesEntitySpecId(long tvsZoneEmployeesEntitySpecId) {
		this.tvsZoneEmployeesEntitySpecId = tvsZoneEmployeesEntitySpecId;
	}
	public long getTvsZoneEmployeesEmployeeNameEntityFieldSpecId() {
		return tvsZoneEmployeesEmployeeNameEntityFieldSpecId;
	}

	public void setTvsZoneEmployeesEmployeeNameEntityFieldSpecId(long tvsZoneEmployeesEmployeeNameEntityFieldSpecId) {
		this.tvsZoneEmployeesEmployeeNameEntityFieldSpecId = tvsZoneEmployeesEmployeeNameEntityFieldSpecId;
	}
	public Long getSkeletonWorkEmployeeFieldSpecId() {
		return skeletonWorkEmployeeFieldSpecId;
	}
	public Long getSkeletonWorkStartsFieldSpecId() {
		return skeletonWorkStartsFieldSpecId;
	}

	public void setSkeletonWorkStartsFieldSpecId(
			Long skeletonWorkStartsFieldSpecId) {
		this.skeletonWorkStartsFieldSpecId = skeletonWorkStartsFieldSpecId;
	}

	public Long getSkeletonWorkEndsFieldSpecId() {
		return skeletonWorkEndsFieldSpecId;
	}

	public void setSkeletonWorkEndsFieldSpecId(Long skeletonWorkEndsFieldSpecId) {
		this.skeletonWorkEndsFieldSpecId = skeletonWorkEndsFieldSpecId;
	}
	
	public String getCaptureLocationInFormUpdateKey() {
		return captureLocationInFormUpdateKey;
	}

	
	
	public long getGlobal_company_custom_entity_form_spec_id() {
		return global_company_custom_entity_form_spec_id;
	}

	public void setGlobal_company_custom_entity_form_spec_id(long global_company_custom_entity_form_spec_id) {
		this.global_company_custom_entity_form_spec_id = global_company_custom_entity_form_spec_id;
	}
	public long getGlobal_company_skeleton_entityId_field_spec_id() {
		return global_company_skeleton_entityId_field_spec_id;
	}

	public void setGlobal_company_skeleton_entityId_field_spec_id(long global_company_skeleton_entityId_field_spec_id) {
		this.global_company_skeleton_entityId_field_spec_id = global_company_skeleton_entityId_field_spec_id;
	}


	public long getGlobal_company_skeleton_entityName_field_spec_id() {
		return global_company_skeleton_entityName_field_spec_id;
	}

	public void setGlobal_company_skeleton_entityName_field_spec_id(
			long global_company_skeleton_entityName_field_spec_id) {
		this.global_company_skeleton_entityName_field_spec_id = global_company_skeleton_entityName_field_spec_id;
	}

	public long getGlobal_company_skeleton_location_field_spec_id() {
		return global_company_skeleton_location_field_spec_id;
	}

	public void setGlobal_company_skeleton_location_field_spec_id(long global_company_skeleton_location_field_spec_id) {
		this.global_company_skeleton_location_field_spec_id = global_company_skeleton_location_field_spec_id;
	}

	public Long getSkeletonWorkNameFieldSpecId() {
		return skeletonWorkNameFieldSpecId;
	}

	
	public Long getSkeletonWorkPhoneNumberFieldSpecId() {
		return skeletonWorkPhoneNumberFieldSpecId;
	}
	
	public String getJobsViaSms() {
		return jobsViaSms;
	}
	public void setJobsViaSms(String jobsViaSms) {
		this.jobsViaSms = jobsViaSms;
	}
	public Boolean getDebugLogEnable() {
		return debugLogEnable;
	}
	public void setDebugLogEnable(Boolean debugLogEnable) {
		this.debugLogEnable = debugLogEnable;
	}
	public Long getSkeletonWorkDescriptionFieldSpecId() {
		return skeletonWorkDescriptionFieldSpecId;
	}
	public void setSkeletonWorkDescriptionFieldSpecId(Long skeletonWorkDescriptionFieldSpecId) {
		this.skeletonWorkDescriptionFieldSpecId = skeletonWorkDescriptionFieldSpecId;
	}
	public String getSkeletonCustomerFieldSpecId() {
		return skeletonCustomerFieldSpecId;
	}
	public void setSkeletonCustomerFieldSpecId(String skeletonCustomerFieldSpecId) {
		this.skeletonCustomerFieldSpecId = skeletonCustomerFieldSpecId;
	}
	public Long getSkeletonWorkProrityFieldSpecId() {
		return skeletonWorkProrityFieldSpecId;
	}
	public void setSkeletonWorkProrityFieldSpecId(Long skeletonWorkProrityFieldSpecId) {
		this.skeletonWorkProrityFieldSpecId = skeletonWorkProrityFieldSpecId;
	}
	public String getSkeletonCustomerAddressFieldSpecId() {
		return skeletonCustomerAddressFieldSpecId;
	}
	public void setSkeletonCustomerAddressFieldSpecId(String skeletonCustomerAddressFieldSpecId) {
		this.skeletonCustomerAddressFieldSpecId = skeletonCustomerAddressFieldSpecId;
	}
	public Long getSkeletonWorkStreetFieldSpecId() {
		return skeletonWorkStreetFieldSpecId;
	}
	public void setSkeletonWorkStreetFieldSpecId(Long skeletonWorkStreetFieldSpecId) {
		this.skeletonWorkStreetFieldSpecId = skeletonWorkStreetFieldSpecId;
	}
	public Long getSkeletonWorkAreaFieldSpecId() {
		return skeletonWorkAreaFieldSpecId;
	}
	public void setSkeletonWorkAreaFieldSpecId(Long skeletonWorkAreaFieldSpecId) {
		this.skeletonWorkAreaFieldSpecId = skeletonWorkAreaFieldSpecId;
	}
	public Long getSkeletonWorkCityFieldSpecId() {
		return skeletonWorkCityFieldSpecId;
	}
	public void setSkeletonWorkCityFieldSpecId(Long skeletonWorkCityFieldSpecId) {
		this.skeletonWorkCityFieldSpecId = skeletonWorkCityFieldSpecId;
	}
	public Long getSkeletonWorkLandMarkFieldSpecId() {
		return skeletonWorkLandMarkFieldSpecId;
	}
	public void setSkeletonWorkLandMarkFieldSpecId(Long skeletonWorkLandMarkFieldSpecId) {
		this.skeletonWorkLandMarkFieldSpecId = skeletonWorkLandMarkFieldSpecId;
	}
	public Long getSkeletonWorkCountryFieldSpecId() {
		return skeletonWorkCountryFieldSpecId;
	}
	public void setSkeletonWorkCountryFieldSpecId(Long skeletonWorkCountryFieldSpecId) {
		this.skeletonWorkCountryFieldSpecId = skeletonWorkCountryFieldSpecId;
	}
	public Long getSkeletonWorkStateFieldSpecId() {
		return skeletonWorkStateFieldSpecId;
	}
	public void setSkeletonWorkStateFieldSpecId(Long skeletonWorkStateFieldSpecId) {
		this.skeletonWorkStateFieldSpecId = skeletonWorkStateFieldSpecId;
	}
	public Long getSkeletonWorkPincodeFieldSpecId() {
		return skeletonWorkPincodeFieldSpecId;
	}
	public void setSkeletonWorkPincodeFieldSpecId(Long skeletonWorkPincodeFieldSpecId) {
		this.skeletonWorkPincodeFieldSpecId = skeletonWorkPincodeFieldSpecId;
	}
	public Long getSkeletonWorkLocationFieldSpecId() {
		return skeletonWorkLocationFieldSpecId;
	}
	public void setSkeletonWorkLocationFieldSpecId(Long skeletonWorkLocationFieldSpecId) {
		this.skeletonWorkLocationFieldSpecId = skeletonWorkLocationFieldSpecId;
	}
	public boolean isCaptureLocationInFormUpdate() {
		return captureLocationInFormUpdate;
	}
	public void setCaptureLocationInFormUpdate(boolean captureLocationInFormUpdate) {
		this.captureLocationInFormUpdate = captureLocationInFormUpdate;
	}
	public static int getChangeTypeAdd() {
		return CHANGE_TYPE_ADD;
	}
	public static int getFormFieldTypeText() {
		return FORM_FIELD_TYPE_TEXT;
	}
	public static int getFormFieldTypeYesNo() {
		return FORM_FIELD_TYPE_YES_NO;
	}
	public static int getFormFieldTypeRichText() {
		return FORM_FIELD_TYPE_RICH_TEXT;
	}
	public static int getFormFieldTypeEmail() {
		return FORM_FIELD_TYPE_EMAIL;
	}
	public static int getFormFieldTypePhone() {
		return FORM_FIELD_TYPE_PHONE;
	}
	public static int getFormFieldTypeUrl() {
		return FORM_FIELD_TYPE_URL;
	}
	public static int getFormFieldTypeTime() {
		return FORM_FIELD_TYPE_TIME;
	}
	public static int getFormFieldTypeImage() {
		return FORM_FIELD_TYPE_IMAGE;
	}
	public static int getFormFieldTypeSignature() {
		return FORM_FIELD_TYPE_SIGNATURE;
	}
	public static int getFormFieldTypeList() {
		return FORM_FIELD_TYPE_LIST;
	}
	public static int getFormFieldTypeEmployee() {
		return FORM_FIELD_TYPE_EMPLOYEE;
	}
	public static int getFormFieldTypeCurrency() {
		return FORM_FIELD_TYPE_CURRENCY;
	}
	public static int getFormFieldTypeMultipickList() {
		return FORM_FIELD_TYPE_MULTIPICK_LIST;
	}
	public static int getFormFieldTypeLocation() {
		return FORM_FIELD_TYPE_LOCATION;
	}
	public static int getFormFieldTypeDateTime() {
		return FORM_FIELD_TYPE_DATE_TIME;
	}
	public static int getFormFieldTypeCountry() {
		return FORM_FIELD_TYPE_COUNTRY;
	}
	public static int getFormFieldTypeFingerPrint() {
		return FORM_FIELD_TYPE_FINGER_PRINT;
	}
	public static int getFormFieldTypeAudio() {
		return FORM_FIELD_TYPE_AUDIO;
	}
	public static int getFormFieldTypeNumberToWord() {
		return FORM_FIELD_TYPE_NUMBER_TO_WORD;
	}
	public static int getFormFieldTypeCustomerType() {
		return FORM_FIELD_TYPE_CUSTOMER_TYPE;
	}
	public static int getFormFieldTypeForm() {
		return FORM_FIELD_TYPE_FORM;
	}
	public static int getFormFieldTypeTimespan() {
		return FORM_FIELD_TYPE_TIMESPAN;
	}
	public static int getFormFieldTypeVideo() {
		return FORM_FIELD_TYPE_VIDEO;
	}
	public static int getFormFieldTypeAutogenerated() {
		return FORM_FIELD_TYPE_AUTOGENERATED;
	}
	public static int getFormFieldTypeLabel() {
		return FORM_FIELD_TYPE_LABEL;
	}
	public static int getFormFieldTypeMultipickCustomer() {
		return FORM_FIELD_TYPE_MULTIPICK_CUSTOMER;
	}
	public static int getFormFieldTypeTerritory() {
		return FORM_FIELD_TYPE_TERRITORY;
	}
	public static int getFormFieldTypeCustomEntity() {
		return FORM_FIELD_TYPE_CUSTOM_ENTITY;
	}
	public static int getFormFieldTypeMultiMedia() {
		return FORM_FIELD_TYPE_MULTI_MEDIA;
	}
	public static int getFormFieldTypeMultipickCustomEntity() {
		return FORM_FIELD_TYPE_MULTIPICK_CUSTOM_ENTITY;
	}
	public static int getFormFieldTypeMonth() {
		return FORM_FIELD_TYPE_MONTH;
	}
	public static int getFormFieldTypeRichTextFormat() {
		return FORM_FIELD_TYPE_RICH_TEXT_FORMAT;
	}
	public static int getFormCustomerFilterTypeCustomersInMyHierarchy() {
		return FORM_CUSTOMER_FILTER_TYPE_CUSTOMERS_IN_MY_HIERARCHY;
	}
	public static int getFormCustomerFilterTypeAllCustomers() {
		return FORM_CUSTOMER_FILTER_TYPE_ALL_CUSTOMERS;
	}
	public static int getFormFieldTypeMultiSelectList() {
		return FORM_FIELD_TYPE_MULTI_SELECT_LIST;
	}
	public static int getFormFieldTypeSingleSelectList() {
		return FORM_FIELD_TYPE_SINGLE_SELECT_LIST;
	}
	public static int getFormCustomerFilterTypeCustomersMappedToMe() {
		return FORM_CUSTOMER_FILTER_TYPE_CUSTOMERS_MAPPED_TO_ME;
	}
	public static int getFormCustomerFilterTypeCustomersMeAndMyHierarchy() {
		return FORM_CUSTOMER_FILTER_TYPE_CUSTOMERS_ME_AND_MY_HIERARCHY;
	}
	public void setGspCropFormSpecUniqueId(String gspCropFormSpecUniqueId) {
		this.gspCropFormSpecUniqueId = gspCropFormSpecUniqueId;
	}
	public void setRootEmpKey(String rootEmpKey) {
		this.rootEmpKey = rootEmpKey;
	}
	public void setGlSTThresholdKey(String glSTThresholdKey) {
		this.glSTThresholdKey = glSTThresholdKey;
	}
	public void setMapToKey(String mapToKey) {
		this.mapToKey = mapToKey;
	}
	public void setJobsViaSmsKey(String jobsViaSmsKey) {
		this.jobsViaSmsKey = jobsViaSmsKey;
	}
	public void setGlGPSThresholdKey(String glGPSThresholdKey) {
		this.glGPSThresholdKey = glGPSThresholdKey;
	}
	public void setGspCropFollowingWorkflow(boolean gspCropFollowingWorkflow) {
		this.gspCropFollowingWorkflow = gspCropFollowingWorkflow;
	}
	public void setJmsDestinationForJobAddOrModifi(String jmsDestinationForJobAddOrModifi) {
		this.jmsDestinationForJobAddOrModifi = jmsDestinationForJobAddOrModifi;
	}
	public void setGspCropNextScheduleInterval(int gspCropNextScheduleInterval) {
		this.gspCropNextScheduleInterval = gspCropNextScheduleInterval;
	}
	public void setFormSpecUniqueId_Of_Approval_form_to_call_rest_call_api(
			String formSpecUniqueId_Of_Approval_form_to_call_rest_call_api) {
		this.formSpecUniqueId_Of_Approval_form_to_call_rest_call_api = formSpecUniqueId_Of_Approval_form_to_call_rest_call_api;
	}
	public void setJco_error_mail_address(String jco_error_mail_address) {
		this.jco_error_mail_address = jco_error_mail_address;
	}
	public void setGlobal_company_customer_form_last_activity_name_skeleton_field_spec_id(
			Long global_company_customer_form_last_activity_name_skeleton_field_spec_id) {
		this.global_company_customer_form_last_activity_name_skeleton_field_spec_id = global_company_customer_form_last_activity_name_skeleton_field_spec_id;
	}
	public void setGlobal_company_customer_form_spec_id(Long global_company_customer_form_spec_id) {
		this.global_company_customer_form_spec_id = global_company_customer_form_spec_id;
	}
	public void setSales_new_leads_form_spec_id(Long sales_new_leads_form_spec_id) {
		this.sales_new_leads_form_spec_id = sales_new_leads_form_spec_id;
	}
	public void setSystem_defined_max_imageSize_for_type_image(Long system_defined_max_imageSize_for_type_image) {
		this.system_defined_max_imageSize_for_type_image = system_defined_max_imageSize_for_type_image;
	}
	public void setSystem_defined_min_imageSize_for_type_image(Long system_defined_min_imageSize_for_type_image) {
		this.system_defined_min_imageSize_for_type_image = system_defined_min_imageSize_for_type_image;
	}
	public void setFizikem_branch_skeleton_entityFieldSpecId(Long fizikem_branch_skeleton_entityFieldSpecId) {
		this.fizikem_branch_skeleton_entityFieldSpecId = fizikem_branch_skeleton_entityFieldSpecId;
	}
	public void setEmp_branch_list_specId(long emp_branch_list_specId) {
		this.emp_branch_list_specId = emp_branch_list_specId;
	}
	public void setGspCropFormFieldSpecformIDUniqueId(String gspCropFormFieldSpecformIDUniqueId) {
		this.gspCropFormFieldSpecformIDUniqueId = gspCropFormFieldSpecformIDUniqueId;
	}
	public void setSerivce_call_Job_form_specId(Long serivce_call_Job_form_specId) {
		this.serivce_call_Job_form_specId = serivce_call_Job_form_specId;
	}
	public void setService_call_visit_type(Long service_call_visit_type) {
		this.service_call_visit_type = service_call_visit_type;
	}
	public void setLatest_client_production_version(String latest_client_production_version) {
		this.latest_client_production_version = latest_client_production_version;
	}
	public void setMediaStoragePath(String mediaStoragePath) {
		this.mediaStoragePath = mediaStoragePath;
	}
	public void setJmsDestination(String jmsDestination) {
		this.jmsDestination = jmsDestination;
	}
	public void setTvsDeliveryWorkSpecId(Long tvsDeliveryWorkSpecId) {
		this.tvsDeliveryWorkSpecId = tvsDeliveryWorkSpecId;
	}
	public void setSkeletonWorkEmployeeFieldSpecId(Long skeletonWorkEmployeeFieldSpecId) {
		this.skeletonWorkEmployeeFieldSpecId = skeletonWorkEmployeeFieldSpecId;
	}
	public void setSkeletonWorkNameFieldSpecId(Long skeletonWorkNameFieldSpecId) {
		this.skeletonWorkNameFieldSpecId = skeletonWorkNameFieldSpecId;
	}
	public void setSkeletonWorkPhoneNumberFieldSpecId(Long skeletonWorkPhoneNumberFieldSpecId) {
		this.skeletonWorkPhoneNumberFieldSpecId = skeletonWorkPhoneNumberFieldSpecId;
	}
	public void setCaptureLocationInFormUpdateKey(String captureLocationInFormUpdateKey) {
		this.captureLocationInFormUpdateKey = captureLocationInFormUpdateKey;
	}
	

	public Long getLtf_fi_workspec_id() {
		return ltf_fi_workspec_id;
	}
	public Long getLtf_rcu_workspec_id() {
		return ltf_rcu_workspec_id;
	}
	public void setLtf_rcu_workspec_id(Long ltf_rcu_workspec_id) {
		this.ltf_rcu_workspec_id = ltf_rcu_workspec_id;
	}
	public Long getLtf_mcm_workspec_id() {
		return ltf_mcm_workspec_id;
	}
	public void setLtf_mcm_workspec_id(Long ltf_mcm_workspec_id) {
		this.ltf_mcm_workspec_id = ltf_mcm_workspec_id;
	}
	public Long getLtf_fi_farm_workspec_id() {
		return ltf_fi_farm_workspec_id;
	}
	public void setLtf_fi_farm_workspec_id(Long ltf_fi_farm_workspec_id) {
		this.ltf_fi_farm_workspec_id = ltf_fi_farm_workspec_id;
	}
	public static String getActionTypeSync() {
		return ACTION_TYPE_SYNC;
	}
	public void setLtf_fi_workspec_id(Long ltf_fi_workspec_id) {
		this.ltf_fi_workspec_id = ltf_fi_workspec_id;
	}
	
	public String getLtf_fi_work_vendor_field_unique_id() {
		return ltf_fi_work_vendor_field_unique_id;
	}

	public Long getTelenor_company_work_action_specId_reject_retailer() {
		return telenor_company_work_action_specId_reject_retailer;
	}
	
	

	public String getCaptureLocationInFormMediaKey() {
		return captureLocationInFormMediaKey;
	}
	
	public String getMapCustomEntitySpecToEmployeeKey() {
		return mapCustomEntitySpecToEmployeeKey;
	}
	
	
	public String getSignOutConditionKey() {
		return signOutConditionKey;
	}
	public String getSignInActivitiyVisibilityKey() {
		return signInActivitiyVisibilityKey;
	}
	public boolean isCaptureLocationInFormMediaUpdate() {
		return captureLocationInFormMediaUpdate;
	}
	public void setCaptureLocationInFormMediaUpdate(boolean captureLocationInFormMediaUpdate) {
		this.captureLocationInFormMediaUpdate = captureLocationInFormMediaUpdate;
	}
	public String getLtf_rcu_work_vendor_field_unique_id() {
		return ltf_rcu_work_vendor_field_unique_id;
	}
	public void setLtf_rcu_work_vendor_field_unique_id(String ltf_rcu_work_vendor_field_unique_id) {
		this.ltf_rcu_work_vendor_field_unique_id = ltf_rcu_work_vendor_field_unique_id;
	}
	public Long getLtf_fi_rcu_vendor_city_spoc_mapping_entitySpecId() {
		return ltf_fi_rcu_vendor_city_spoc_mapping_entitySpecId;
	}
	public void setLtf_fi_rcu_vendor_city_spoc_mapping_entitySpecId(Long ltf_fi_rcu_vendor_city_spoc_mapping_entitySpecId) {
		this.ltf_fi_rcu_vendor_city_spoc_mapping_entitySpecId = ltf_fi_rcu_vendor_city_spoc_mapping_entitySpecId;
	}
	public Long getLtf_fi_rcu_vendor_city_spoc_mapping_spoc_id_entityFieldSpecId() {
		return ltf_fi_rcu_vendor_city_spoc_mapping_spoc_id_entityFieldSpecId;
	}
	public void setLtf_fi_rcu_vendor_city_spoc_mapping_spoc_id_entityFieldSpecId(
			Long ltf_fi_rcu_vendor_city_spoc_mapping_spoc_id_entityFieldSpecId) {
		this.ltf_fi_rcu_vendor_city_spoc_mapping_spoc_id_entityFieldSpecId = ltf_fi_rcu_vendor_city_spoc_mapping_spoc_id_entityFieldSpecId;
	}
	public String getLtf_fi_work_city_field_unique_id() {
		return ltf_fi_work_city_field_unique_id;
	}
	public void setLtf_fi_work_city_field_unique_id(String ltf_fi_work_city_field_unique_id) {
		this.ltf_fi_work_city_field_unique_id = ltf_fi_work_city_field_unique_id;
	}
	public String getLtf_rcu_work_city_field_unique_id() {
		return ltf_rcu_work_city_field_unique_id;
	}
	public void setLtf_rcu_work_city_field_unique_id(String ltf_rcu_work_city_field_unique_id) {
		this.ltf_rcu_work_city_field_unique_id = ltf_rcu_work_city_field_unique_id;
	}
	public void setSignInActivitiyVisibilityKey(String signInActivitiyVisibilityKey) {
		this.signInActivitiyVisibilityKey = signInActivitiyVisibilityKey;
	}
	public void setSignOutConditionKey(String signOutConditionKey) {
		this.signOutConditionKey = signOutConditionKey;
	}
	public void setTelenor_company_work_action_specId_reject_retailer(
			Long telenor_company_work_action_specId_reject_retailer) {
		this.telenor_company_work_action_specId_reject_retailer = telenor_company_work_action_specId_reject_retailer;
	}
	public void setLtf_fi_work_vendor_field_unique_id(String ltf_fi_work_vendor_field_unique_id) {
		this.ltf_fi_work_vendor_field_unique_id = ltf_fi_work_vendor_field_unique_id;
	}
	public void setMapCustomEntitySpecToEmployeeKey(String mapCustomEntitySpecToEmployeeKey) {
		this.mapCustomEntitySpecToEmployeeKey = mapCustomEntitySpecToEmployeeKey;
	}
	public void setCaptureLocationInFormMediaKey(String captureLocationInFormMediaKey) {
		this.captureLocationInFormMediaKey = captureLocationInFormMediaKey;
	}
	public Integer getXeroxCompanyId() {
		return xeroxCompanyId;
	}
	public String getPushNotificationDefaultMessage() {
		return pushNotificationDefaultMessage;
	}

	public String getWindowsPushNotificationAccessTokenHeaderContentType() {
		return windowsPushNotificationAccessTokenHeaderContentType;
	}
	public String getWindowsPushNotificationAccessTokenParameterString() {
		return windowsPushNotificationAccessTokenParameterString;
	}
	
	public String getWindowsPushNotificationAccessTokenUrl() {
		return windowsPushNotificationAccessTokenUrl;
	}
	public String getMediaBaseUrl() {
		return mediaBaseUrl;
	}
	public String getSupportingImgExtn() {
		return supportingImgExtn;
	}

	public String getGspCropquantitySectionFieldSpecUniqueId() {
		return gspCropquantitySectionFieldSpecUniqueId;
	}
	
	public static String getProject() {
		return project;
	}
}

